module.exports = {
    future: {
        // removeDeprecatedGapUtilities: true,
        // purgeLayersByDefault: true,
    },
    purge: [
        './resources/**/*.php',
        './resources/**/*.html',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            spacing: {
                '72': '18rem',
            },
            height: () => ({
                '1/2': '50%',
                '1/3': '33.333333%',
                '2/3': '66.666667%',
                '1/4': '25%',
                '2/4': '50%',
                '3/4': '75%',
                '1/5': '20%',
                '2/5': '40%',
                '3/5': '60%',
                '4/5': '80%',
                '1/6': '16.666667%',
                '2/6': '33.333333%',
                '3/6': '50%',
                '4/6': '66.666667%',
                '5/6': '83.333333%',
                '1/12': '8.333333%',
                '2/12': '16.666667%',
                '3/12': '25%',
                '4/12': '33.333333%',
                '5/12': '41.666667%',
                '6/12': '50%',
                '7/12': '58.333333%',
                '8/12': '66.666667%',
                '9/12': '75%',
                '10/12': '83.333333%',
                '11/12': '91.666667%',
            }),
            maxHeight: (theme, { breakpoints }) => ({
                none: 'none',
                xs: '20rem',
                sm: '24rem',
                md: '28rem',
                lg: '32rem',
                xl: '36rem',
                '2xl': '42rem',
                '3xl': '48rem',
                '4xl': '56rem',
                '5xl': '64rem',
                '6xl': '72rem',
                full: '100%',
                ...breakpoints(theme('screens')),
                ...theme('spacing'),
            }),
            fontFamily: {
                'lato': ['Lato', 'sans-serif'],
                'signerica': ['Signerica', 'sans-serif'],
            },
            fontSize: {
                logo: '8rem',
                'logo-mobile': '4rem',
                xxs: '0.4rem',
            },
            letterSpacing: {
                logo: '1rem',
                'logo-mobile': '0.6rem',
                about: '0.5rem',
            },
            zIndex: {
                behind: '-1',
            },
            backgroundOpacity: {
                '10': '0.10',
            },
            backdropFilter: {
                'none': 'none',
                'blur-1': 'blur(1px)',
                'blur-3': 'blur(3px)',
                'blur-5': 'blur(5px)',
                'blur-10': 'blur(10px)',
                'blur-15': 'blur(15px)',
                'blur-20': 'blur(20px)',
            },
        },
    },
    variants: {
        opacity: ['responsive', 'hover', 'focus', 'disabled'],
    },
    plugins: [
        require('tailwindcss-filters'),
    ],
};
